/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RATIOPOL4EXPPDF
#define RATIOPOL4EXPPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

TString  nameParameters[] = {"p0","p1","p2","p3","p4","p5","N_bkg","N_sig","mean","width"};

class RatioPol4ExpPdf : public RooAbsPdf {
public:
  RatioPol4ExpPdf() {} ;
  RatioPol4ExpPdf(const char *name, const char *title,
	      RooAbsReal& _x,
        RooAbsReal& _A,
	      RooAbsReal& _B,
        RooAbsReal& _C,
        RooAbsReal& _D,
        RooAbsReal& _E,
	      RooAbsReal& _P0,
	      RooAbsReal& _P1,
        RooAbsReal& _P2,
        RooAbsReal& _P3,
        RooAbsReal& _P4,
        RooAbsReal& _P5);
  RatioPol4ExpPdf(const RatioPol4ExpPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RatioPol4ExpPdf(*this,newname); }
  inline virtual ~RatioPol4ExpPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy D ;
  RooRealProxy E ;
  RooRealProxy P0 ;
  RooRealProxy P1 ;
  RooRealProxy P2 ;
  RooRealProxy P3 ;
  RooRealProxy P4 ;
  RooRealProxy P5 ;

  Double_t evaluate() const ;

private:

  ClassDef(RatioPol4ExpPdf,1) // Your description goes here...
};

#endif
