/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RATIOVWGPDF
#define RATIOVWGPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RatioVWGPdf : public RooAbsPdf {
public:
  RatioVWGPdf() {} ;
  RatioVWGPdf(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _A,
	    RooAbsReal& _B,
      RooAbsReal& _C,
      RooAbsReal& _D,
      RooAbsReal& _E,
      RooAbsReal& _F,
      RooAbsReal& _G,
      RooAbsReal& _H,
      RooAbsReal& _I);
  RatioVWGPdf(const RatioVWGPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RatioVWGPdf(*this,newname); }
  inline virtual ~RatioVWGPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  RooRealProxy C ;
  RooRealProxy D ;
  RooRealProxy E ;
  RooRealProxy F ;
  RooRealProxy G ;
  RooRealProxy H ;
  RooRealProxy I ;

  Double_t evaluate() const ;

private:

  ClassDef(RatioVWGPdf,1) // Your description goes here...
};

#endif
