---
inputs:
  pathPtDep: /Users/lucamicheletti/GITHUB/dq_fitter/analysis/LHC23_pass4_full/centrality_10_30/pt_dependence_narrow_bins
  #ptMin: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0]
  #ptMax: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 15.0]
  ptMin: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0]
  ptMax: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 15.0]
  varNames: ["sig_Jpsi", "width_Jpsi", "mean_Jpsi"]
  varIndex: 4 #index of the variable to write properly the pT,y,centr bin on the txt file (see num[varIndex] in utils_library.py)
  #varNames: ["sig_Jpsi", "width_Jpsi", "mean_Jpsi", "ratio"]
