---
inputs:
  pathPtDep: /Users/garetti/dq_fitter_tails/analysis/muonLowPt210SigmaPDCA/pp_ref/output
  #ptMin: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0]
  #ptMax: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 15.0]
  ptMin: [0.0]
  ptMax: [20.0]
  varNames: ["sig_Jpsi", "width_Jpsi", "mean_Jpsi", "ratio", "sgnf_Jpsi", "sgnf_Psi2s", "sOverB_Jpsi", "sOverB_Psi2s", "chi2"]
  varIndex: 2 #index of the variable to write properly the pT,y,centr bin on the txt file (see num[varIndex] in utils_library.py)
  fileNames: ["output", "multi_trial"]
  #varNames: ["sig_Jpsi", "width_Jpsi", "mean_Jpsi", "ratio"]
