---
inputs:
  pathPtDep: /Users/lucamicheletti/GITHUB/dq_fitter/analysis/LHC24_pass1_skimmed/pt_dependence_noBkg_data_tails
  #ptMin: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0]
  #ptMax: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0, 12.0, 15.0]
  ptMin: [0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0, 15.0]
  ptMax: [0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0, 15.0, 20.0]
  varNames: ["sig_Jpsi", "width_Jpsi", "mean_Jpsi", "sig_Psi2s"]
  varIndex: 2 #index of the variable to write properly the pT,y,centr bin on the txt file (see num[varIndex] in utils_library.py)
  #varNames: ["sig_Jpsi", "width_Jpsi", "mean_Jpsi", "ratio"]
