name: ROOT Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # Usa direttamente l'immagine ufficiale ROOT come container
    container:
      image: rootproject/root:6.30.06  # puoi cambiare la versione

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v
