name: ROOT Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rootproject/root:latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python venv
        run: |
          apt-get update
          apt-get install -y python3-venv python3-pip
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip pytest
          pip install pytest matplotlib
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest -v