name: ROOT Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rootproject/root:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pip & pytest
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install --upgrade pip pytest
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      - name: Run tests
        run: pytest -v