name: ROOT Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rootproject/root:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python & dependencies
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip pytest
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -v